"""Stub Sentinel — Phase A pass-through.

Polls the pending queue, passes every slice with a modality-derived
trust score, and emits a batch-summary audit slice on
``substrate.self_state``.

Real defense logic (prompt-injection detection, content poisoning,
source impersonation) lands in Phase B+. This stub exists so the
pending → passed lifecycle and the SKIP-LOCKED concurrency contract
are exercised from day one.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from substrate.agents.base import SubAgent
from substrate.storage.types import Modality, SentinelState

if TYPE_CHECKING:  # pragma: no cover
    from substrate.facade import Substrate


# Trust score by modality. Source-derived defense is Phase B+; for now
# we just say "text from random users gets less trust than structured
# events generated by Hermes itself".
_TRUST_BY_MODALITY: dict[Modality, float] = {
    Modality.TEXT: 0.5,
    Modality.STRUCTURED_EVENT: 0.7,
    Modality.BINARY_BLOB: 0.7,
    Modality.SIGNAL: 0.3,
}


def _trust_for_modality(modality: Modality) -> float:
    """Phase A trust score lookup. Phase B+ replaces this with a real
    function of (modality, source, content, sender_reputation, ...).
    """
    return _TRUST_BY_MODALITY.get(modality, 0.5)


class StubSentinel(SubAgent):
    """Phase A Sentinel — passes everything.

    Floor intensity = FULL, always (enforced by the base class). The
    tick runs every 200ms at FULL.

    A SKIP-LOCKED batch read + multi-row UPDATE means multiple Sentinel
    instances (Phase B+ horizontal scaling) don't double-decide rows
    in the same batch. Audit summary is emitted **outside** the batch
    transaction so a slow audit emit doesn't extend the lock window.
    """

    name = "sentinel"
    is_sentinel = True

    def __init__(self, substrate: "Substrate") -> None:
        super().__init__(substrate)
        # Batch size — keep small so each tick finishes quickly and
        # other Sentinel instances can grab their own slices.
        self._batch_limit = 100

    async def tick(self) -> None:
        import hermes_db
        from substrate.l0.api import commit_slice

        from substrate.storage import DEFAULT_STRUCTURED_PROFILE  # noqa: F401

        # 1) Read pending batch + decide everyone, all in one txn so a
        #    partial failure leaves the pending queue unchanged.
        async with hermes_db.transaction() as conn:
            batch = await self._substrate.slices.list_pending(
                conn, limit=self._batch_limit, lock=True
            )
            if not batch:
                return

            decisions = [
                (
                    s.slice_id,
                    SentinelState.PASSED,
                    _trust_for_modality(s.payload_modality),
                    None,  # reason: stub Sentinel has no opinion
                )
                for s in batch
            ]
            await self._substrate.slices.decide_many(conn, decisions)

        # 2) Emit the batch summary on substrate.self_state. This is
        #    its own commit (no shared txn) so the audit landing is
        #    independent of the Sentinel batch transaction.
        await self._emit_batch_summary(batch)

    async def _emit_batch_summary(self, batch: list) -> None:
        """Emit one structured-event slice summarising the batch.

        The audit row keeps the slice IDs as strings (UUIDs are not
        JSON-natively serialisable; the codec round-trips dicts but
        each leaf has to be JSON-compatible).
        """
        from substrate.l0.api import commit_slice

        self_state = await self._substrate.streams.get_by_name(
            "substrate.self_state"
        )
        if self_state is None:
            self._log.warning(
                "substrate.self_state stream missing; can't emit audit"
            )
            return

        await commit_slice(
            self._substrate,
            stream_id=self_state.stream_id,
            payload={
                "event": "sentinel_batch_decision",
                "count": len(batch),
                "decisions": "passed",
                "slice_ids": [str(s.slice_id) for s in batch],
            },
            event_time_world=datetime.now(timezone.utc),
            metadata={"agent": "sentinel"},
        )


__all__ = ["StubSentinel", "_trust_for_modality"]
