"""Sentinel — guards L0 ingestion.

Polls the pending queue and decides each slice ``passed`` (with a trust
score) or ``quarantined``. By default it's the Phase A pass-through
(modality-derived trust, quarantines nothing); when
``HERMES_SUBSTRATE_SENTINEL_DEFENSE=1`` it runs the real content defense
(``sentinel_defense.assess`` — heuristic prompt-injection / impersonation /
exfiltration detection) and quarantines hostile slices so they never reach
consolidation or recall (MVS §6.2).

The defense is gated OFF by default because quarantining is a behaviour
change (a false positive silently drops a slice from recall); operators
opt in after tuning. The pass-through path and the SKIP-LOCKED concurrency
contract are unchanged.
"""

from __future__ import annotations

import os
from typing import TYPE_CHECKING

from substrate.agents import sentinel_defense
from substrate.agents.base import SubAgent
from substrate.storage.types import Modality, SentinelState

if TYPE_CHECKING:  # pragma: no cover
    from substrate.facade import Substrate


# Trust score by modality. Source-derived defense is Phase B+; for now
# we just say "text from random users gets less trust than structured
# events generated by Hermes itself".
_TRUST_BY_MODALITY: dict[Modality, float] = {
    Modality.TEXT: 0.5,
    Modality.STRUCTURED_EVENT: 0.7,
    Modality.BINARY_BLOB: 0.7,
    Modality.SIGNAL: 0.3,
}


def _trust_for_modality(modality: Modality) -> float:
    """Phase A trust score lookup. Phase B+ replaces this with a real
    function of (modality, source, content, sender_reputation, ...).
    """
    return _TRUST_BY_MODALITY.get(modality, 0.5)


class StubSentinel(SubAgent):
    """Phase A Sentinel — passes everything.

    Floor intensity = FULL, always (enforced by the base class). The
    tick runs every 200ms at FULL.

    A SKIP-LOCKED batch read + multi-row UPDATE means multiple Sentinel
    instances (Phase B+ horizontal scaling) don't double-decide rows
    in the same batch. Audit summary is emitted **outside** the batch
    transaction so a slow audit emit doesn't extend the lock window.
    """

    name = "sentinel"
    is_sentinel = True

    def __init__(self, substrate: "Substrate") -> None:
        super().__init__(substrate)
        # Batch size — keep small so each tick finishes quickly and
        # other Sentinel instances can grab their own slices.
        self._batch_limit = 100

    @staticmethod
    def _defense_enabled() -> bool:
        raw = (os.environ.get("HERMES_SUBSTRATE_SENTINEL_DEFENSE") or "").strip().lower()
        return raw in {"1", "true", "yes", "on"}

    def _decide(self, s) -> tuple:
        """Return a ``decide_many`` tuple for one pending slice.

        Pass-through (default) → PASSED at modality trust. With defense on,
        the content assessor may QUARANTINE or reduce trust.
        """
        base = _trust_for_modality(s.payload_modality)
        if not self._defense_enabled():
            return (s.slice_id, SentinelState.PASSED, base, None)
        v = sentinel_defense.assess(s.payload, s.payload_modality, base)
        return (s.slice_id, v.state, v.trust_score, v.reason)

    async def tick(self) -> None:
        import hermes_db

        # 1) Read pending batch + decide everyone, all in one txn so a
        #    partial failure leaves the pending queue unchanged.
        async with hermes_db.transaction() as conn:
            batch = await self._substrate.slices.list_pending(
                conn, limit=self._batch_limit, lock=True
            )
            if not batch:
                return

            decisions = [self._decide(s) for s in batch]
            await self._substrate.slices.decide_many(conn, decisions)

        # 2) Record the batch summary as operational telemetry (NOT a
        #    perceptual slice). Outside the batch txn so a slow write
        #    doesn't extend the lock window.
        await self._emit_batch_summary(batch, decisions)

    async def _emit_batch_summary(self, batch: list, decisions: list) -> None:
        """Record one telemetry row summarising the batch.

        Slice IDs are kept as strings (UUIDs aren't JSON-native). With
        defense on, the summary records how many slices were quarantined
        and why.

        Writes to ``substrate_telemetry`` (non-perceptual), not as a slice
        on ``substrate.self_state``. This is what closes the historical
        self-audit recursion: a telemetry row never enters the pending
        queue, so the Sentinel's next tick can't pick it up and emit an
        audit-about-the-audit. (2026-05-26 incident: 398k self-audit
        slices in ~12 hours, when these were born-pending L0 slices.)
        """
        from substrate.telemetry import write as telemetry_write

        quarantined = [d for d in decisions if d[1] is SentinelState.QUARANTINED]
        passed = len(decisions) - len(quarantined)

        await telemetry_write(
            self._substrate,
            agent="sentinel",
            event="sentinel_batch_decision",
            payload={
                "count": len(batch),
                "passed": passed,
                "quarantined": len(quarantined),
                "quarantine_reasons": [d[3] for d in quarantined if d[3]],
                "slice_ids": [str(s.slice_id) for s in batch],
            },
        )


__all__ = ["StubSentinel", "_trust_for_modality"]
