"""Sentinel — guards L0 ingestion.

Polls the pending queue and decides each slice ``passed`` (with a trust
score) or ``quarantined``. By default it's the Phase A pass-through
(modality-derived trust, quarantines nothing); when
``HERMES_SUBSTRATE_SENTINEL_DEFENSE=1`` it runs the real content defense
(``sentinel_defense.assess`` — heuristic prompt-injection / impersonation /
exfiltration detection) and quarantines hostile slices so they never reach
consolidation or recall (MVS §6.2).

The defense is gated OFF by default because quarantining is a behaviour
change (a false positive silently drops a slice from recall); operators
opt in after tuning. The pass-through path and the SKIP-LOCKED concurrency
contract are unchanged.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import TYPE_CHECKING

from substrate.agents import sentinel_defense
from substrate.agents.base import SubAgent
from substrate.storage.types import Modality, SentinelState

if TYPE_CHECKING:  # pragma: no cover
    from substrate.facade import Substrate


# Trust score by modality. Source-derived defense is Phase B+; for now
# we just say "text from random users gets less trust than structured
# events generated by Hermes itself".
_TRUST_BY_MODALITY: dict[Modality, float] = {
    Modality.TEXT: 0.5,
    Modality.STRUCTURED_EVENT: 0.7,
    Modality.BINARY_BLOB: 0.7,
    Modality.SIGNAL: 0.3,
}


def _trust_for_modality(modality: Modality) -> float:
    """Phase A trust score lookup. Phase B+ replaces this with a real
    function of (modality, source, content, sender_reputation, ...).
    """
    return _TRUST_BY_MODALITY.get(modality, 0.5)


class StubSentinel(SubAgent):
    """Phase A Sentinel — passes everything.

    Floor intensity = FULL, always (enforced by the base class). The
    tick runs every 200ms at FULL.

    A SKIP-LOCKED batch read + multi-row UPDATE means multiple Sentinel
    instances (Phase B+ horizontal scaling) don't double-decide rows
    in the same batch. Audit summary is emitted **outside** the batch
    transaction so a slow audit emit doesn't extend the lock window.
    """

    name = "sentinel"
    is_sentinel = True

    def __init__(self, substrate: "Substrate") -> None:
        super().__init__(substrate)
        # Batch size — keep small so each tick finishes quickly and
        # other Sentinel instances can grab their own slices.
        self._batch_limit = 100

    @staticmethod
    def _defense_enabled() -> bool:
        raw = (os.environ.get("HERMES_SUBSTRATE_SENTINEL_DEFENSE") or "").strip().lower()
        return raw in {"1", "true", "yes", "on"}

    def _decide(self, s) -> tuple:
        """Return a ``decide_many`` tuple for one pending slice.

        Pass-through (default) → PASSED at modality trust. With defense on,
        the content assessor may QUARANTINE or reduce trust.
        """
        base = _trust_for_modality(s.payload_modality)
        if not self._defense_enabled():
            return (s.slice_id, SentinelState.PASSED, base, None)
        v = sentinel_defense.assess(s.payload, s.payload_modality, base)
        return (s.slice_id, v.state, v.trust_score, v.reason)

    async def tick(self) -> None:
        import hermes_db

        # 1) Read pending batch + decide everyone, all in one txn so a
        #    partial failure leaves the pending queue unchanged.
        async with hermes_db.transaction() as conn:
            batch = await self._substrate.slices.list_pending(
                conn, limit=self._batch_limit, lock=True
            )
            if not batch:
                return

            decisions = [self._decide(s) for s in batch]
            await self._substrate.slices.decide_many(conn, decisions)

        # 2) Emit the batch summary on substrate.self_state. This is
        #    its own commit (no shared txn) so the audit landing is
        #    independent of the Sentinel batch transaction.
        await self._emit_batch_summary(batch, decisions)

    async def _emit_batch_summary(self, batch: list, decisions: list) -> None:
        """Emit one structured-event slice summarising the batch.

        The audit row keeps the slice IDs as strings (UUIDs are not
        JSON-natively serialisable; the codec round-trips dicts but
        each leaf has to be JSON-compatible). With defense on, the
        summary records how many slices were quarantined and why.
        """
        from substrate.l0.api import commit_slice

        self_state = await self._substrate.streams.get_by_name(
            "substrate.self_state"
        )
        if self_state is None:
            self._log.warning(
                "substrate.self_state stream missing; can't emit audit"
            )
            return

        quarantined = [d for d in decisions if d[1] is SentinelState.QUARANTINED]
        passed = len(decisions) - len(quarantined)

        await commit_slice(
            self._substrate,
            stream_id=self_state.stream_id,
            payload={
                "event": "sentinel_batch_decision",
                "count": len(batch),
                "passed": passed,
                "quarantined": len(quarantined),
                "quarantine_reasons": [d[3] for d in quarantined if d[3]],
                "slice_ids": [str(s.slice_id) for s in batch],
            },
            event_time_world=datetime.now(timezone.utc),
            metadata={"agent": "sentinel"},
            # MANDATORY: without born_passed=True this audit slice
            # lands in 'pending' state and the Sentinel's next tick
            # picks it up, decides it 'passed', emits ANOTHER audit
            # about that audit — recursing forever. 2026-05-26 prod
            # incident: 398k self-audit slices in ~12 hours. See the
            # ``commit_slice`` docstring for the full rationale.
            born_passed=True,
        )


__all__ = ["StubSentinel", "_trust_for_modality"]
